---
- name: Get gateway pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: get

- name: Remove current gateway pod
  containers.podman.podman_pod:
    name: "{{ env + '-gateway-' + current_pod }}"
    state: absent
  when: current_pod != []
- name: Remove failed gateway pod
  containers.podman.podman_pod:
    name: "{{ env + '-gateway-' + failed_pod }}"
    state: absent
  when: failed_pod != []

- name: Create gateway volumes
  ansible.builtin.include_role:
    name: podman-volume
  vars:
    service: gateway
    container_type: app
    volume_mountpoint: "{{ item }}"
  loop:
    - /etc/haproxy
    - /etc/pki/tls/private

- name: Create gateway config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/haproxy'|replace('/', '-') }}/_data/haproxy.cfg"

- name: Create step-ca config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/pki/tls/private'|replace('/', '-') }}/_data/{{ item }}"
  loop:
    - consul.crt
    - consul.crt.key
    - git.crt
    - git.crt.key
    - kuma.crt
    - kuma.crt.key
    - minio.crt
    - minio.crt.key
    - registry.crt
    - registry.crt.key
    - repo.crt
    - repo.crt.key
    - resolver.crt
    - resolver.crt.key
    - auth.crt
    - auth.crt.key
    - keycloak.crt
    - keycloak.crt.key
    - pgadmin.crt
    - pgadmin.crt.key
    - rundeck.crt
    - rundeck.crt.key

- name: Create gateway pod
  ansible.builtin.import_role:
    name: podman-pod
  vars:
    service: gateway
    pod_publish:
      - "80:80"
      - "443:443"
      - "2222:2222"
      - "8443:8443"
- name: Create gateway container
  ansible.builtin.import_role:
    name: podman-container
  vars:
    service: gateway
    container_image: "{{ lookup('consul_kv', env + '/defaults/registry_url', host=consul_host) + '/bootstrap/haproxy:latest' }}"
    container_type: app
    container_volumes:
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/haproxy'|replace('/', '-') }}:/etc/haproxy:z"
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/pki/tls/private'|replace('/', '-') }}:/etc/pki/tls/private:z"
    container_secrets:

- name: Create gateway mesh
  ansible.builtin.import_role:
    name: mesh
  vars:
    service: gateway
    mesh_gateway: haproxy
    mesh_inbound:
    mesh_outbound:
      - service: kuma
        port: "12001"
      - service: step-ca
        port: "12002"
      - service: consul-api
        port: "12003"
      - service: minio-console
        port: "12004"
      - service: nexus-repo
        port: "12005"
      - service: nexus-registry
        port: "12006"
      - service: gitlab-web
        port: "12007"
      - service: gitlab-ssh
        port: "12008"
      - service: resolver-web
        port: "12009"
      - service: keycloak-web
        port: "12010"
      - service: keycloak-mgmt
        port: "12011"
      - service: pgadmin
        port: "12012"
      - service: rundeck
        port: "12013"

- name: Set gateway pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: set
