---
- name: Get gateway pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: get

- name: Remove current gateway pod
  containers.podman.podman_pod:
    name: "{{ env + '-gateway-' + current_pod }}"
    state: absent
  when: current_pod != []
- name: Remove failed gateway pod
  containers.podman.podman_pod:
    name: "{{ env + '-gateway-' + failed_pod }}"
    state: absent
  when: failed_pod != []

- name: Create gateway volumes
  ansible.builtin.include_role:
    name: podman-volume
  vars:
    service: gateway
    container_type: app
    volume_mountpoint: /etc/haproxy

- name: Create gateway config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/haproxy'|replace('/', '-') }}/_data/haproxy.cfg"

- name: Create gateway pod
  ansible.builtin.import_role:
    name: podman-pod
  vars:
    service: gateway
    pod_publish:
      - "80:80"
      - "443:443"
      - "2222:2222"
      - "8443:8443"
- name: Create gateway container
  ansible.builtin.import_role:
    name: podman-container
  vars:
    service: gateway
    container_image: "{{ lookup('consul_kv', env + '/defaults/registry_url', host=consul_host) + '/bootstrap/haproxy:latest' }}"
    container_type: app
    container_volumes:
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/haproxy'|replace('/', '-') }}://etc/haproxy:z"
    container_secrets:

- name: Create gateway mesh
  ansible.builtin.import_role:
    name: mesh
  vars:
    service: gateway
    mesh_gateway: haproxy
    mesh_inbound:
    mesh_outbound:
      - service: kuma
        port: "12001"
      - service: minio-console
        port: "12002"
      - service: nexus-repo
        port: "12003"
      - service: nexus-registry
        port: "12004"
      - service: gitlab-web
        port: "12005"
      - service: gitlab-ssh
        port: "12006"
      - service: step-ca
        port: "12007"

- name: Set gateway pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: set
