---
- name: Generate deployment id
  ansible.builtin.include_role:
    name: pod-id
- name: Deploy gateway pod
  ansible.builtin.include_role:
    name: podman-pod
    tasks_from: present
  vars:
    pod_name: "{{ current_pod_name }}"
    pod_publish:
      - "80:80"
      - "443:443"
      - "2222:2222"
- name: Deploy gateway container
  ansible.builtin.include_role:
    name: podman-container
    tasks_from: present
  vars:
    container_name: "{{ current_app_container_name }}"
    container_pod: "{{ current_pod_name }}"
    container_image: "registry.lab.skarbek.name/bootstrap/nginx:latest"
    container_catatonit: false
    container_volumes:
      - container_volume_mountpoint: /etc/nginx/conf.d
        container_volume_type: zfs
      - container_volume_mountpoint: /etc/nginx/stream.d
        container_volume_type: zfs
      - container_volume_mountpoint: /etc/pki/tls/private
        container_volume_type: zfs
      - container_volume_mountpoint: /var/log/nginx
        container_volume_type: zfs
      - container_volume_mountpoint: /var/log/journal
        container_volume_type: zfs
- name: Start gateway pod
  ansible.builtin.include_role:
    name: podman-pod
    tasks_from: started
  vars:
    pod_name: "{{ current_pod_name }}"
- name: Start gateway container
  ansible.builtin.include_role:
    name: podman-container
    tasks_from: started
  vars:
    container_name: "{{ current_app_container_name }}"
- name: Deploy gateway mesh dataplane
  ansible.builtin.include_role:
    name: pod-mesh
    tasks_from: present
  vars:
    mesh_config:
      mesh_gateway: nginx
      #mesh_outbound:
      #  - port:
      #    service:
