FROM repo.skarbek.name/h-con-infra/ubi10:10.2

COPY rootfs/ /

RUN <<EOF
    dnf -y install vsftpd
    dnf clean all
    mkdir -p /usr/share/vsftpd
    mv /etc/vsftpd/* /usr/share/vsftpd/
EOF

CMD ["/usr/bin/dinit", "--container"]

VOLUME /etc/vsftpd
VOLUME /var/ftp
