ARG BASE_IMAGES_REPO

FROM ${BASE_IMAGES_REPO}/ubi10-minimal:latest

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    microdnf -y install vsftpd
    microdnf clean all
    mkdir -p /usr/share/vsftpd
    mv /etc/vsftpd/* /usr/share/vsftpd/
EOF

VOLUME /etc/vsftpd
VOLUME /var/ftp
