ARG PROJ_IMAGES_REPO

FROM ${PROJ_IMAGES_REPO}/ubi10-minimal:latest

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    curl -Lo /usr/bin/unftp https://repo.skarbek.name/repository/p-raw-github/bolcom/unFTP/releases/download/v0.15.2/unftp_x86_64-unknown-linux-gnu
    chmod 0755 /usr/bin/unftp
EOF

VOLUME /var/lib/unftp
