ARG BASE_IMAGES_REPO

FROM ${BASE_IMAGES_REPO}/ubi10-minimal:latest

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    microdnf -y install unzip openssl
    microdnf clean all
    curl -Lo /tmp/rustfs.zip https://repo.skarbek.name/repository/h-raw-infra/rustfs/1.0.0-beta.6/rustfs.zip
    unzip -d /usr/local/bin/ /tmp/rustfs.zip
    rm /tmp/rustfs.zip
    chmod 0755 /usr/local/bin/rustfs
    cd /usr/local/bin
    curl -L https://repo.skarbek.name/repository/h-raw-infra/rustfs-cli/0.1.18/rustfs-cli.tar.gz|tar xz
    chmod 0755 /usr/local/bin/rc
EOF

VOLUME /var/lib/rustfs
