FROM repo.skarbek.name/p-con-docker/redhat/ubi10:latest

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    envsubst < /etc/yum.repos.d/all.tmpl > /etc/yum.repos.d/all.repo
    rm /etc/yum.repos.d/ubi.repo /etc/yum.repos.d/all.tmpl
    dnf -y install buildah fuse-overlayfs catatonit gettext-envsubst
    dnf clean all
EOF

ENTRYPOINT ["/usr/libexec/catatonit/catatonit", "--"]
