---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.unarchive:
        src: "https://github.com/oven-sh/bun/releases/download/bun-v{{ bun_version }}/bun-linux-x64.zip"
        dest: "{{ result_tempfile.path }}"
        remote_src: true
    - ansible.builtin.file:
        dest: "{{ container_path }}/usr/local/bin/bun"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.copy:
        src: "{{ result_tempfile.path }}/bun-linux-x64/bun"
        dest: "{{ container_path }}/usr/local/bin/"
        force: true
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} useradd --comment 'Bun' --create-home --shell /usr/bin/bash bun"
        - "buildah config --user bun {{ container_uuid }}"
        - "buildah config --workingdir /home/bun {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
