---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ result_tempfile.path }}{{ item.dest }}"
        force: true
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - url: "{{ bun_public_url }}"
          dest: "/bun-linux-x64.zip"
      loop_control:
        label: "{{ item.dest }}"
      when: "not use_repository"
    - ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ result_tempfile.path }}{{ item.dest }}"
        force: true
        username: "{{ repository_username }}"
        password: "{{ repository_password }}"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - url: "{{ bun_proxy_url }}"
          dest: "/bun-linux-x64.zip"
      loop_control:
        label: "{{ item.dest }}"
      when: "use_repository"
    - ansible.builtin.unarchive:
        src: "{{ result_tempfile.path }}/bun-linux-x64.zip"
        dest: "{{ result_tempfile.path }}"
    - ansible.builtin.file:
        dest: "{{ container_path }}/usr/local/bin/bun"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.copy:
        src: "{{ result_tempfile.path }}/bun-linux-x64/bun"
        dest: "{{ container_path }}/usr/local/bin/"
        force: true
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} useradd --comment 'Bun' --create-home --shell /usr/bin/bash bun"
        - "buildah config --user bun {{ container_uuid }}"
        - "buildah config --workingdir /home/bun {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
