---
bootstrap:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - bootstrap/**/*
  image: repo.skarbek.name/p-con-docker/redhat/ubi10:10.2
  script: |
    dnf clean all
    dnf -y install buildah fuse-overlayfs
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/buildah --network=host ./bootstrap/
    buildah push $REPO_URL/buildah
ubi10:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - ubi10/**/*
  needs:
    - job: bootstrap
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/ubi10:10.2 --network=host ./ubi10/
    buildah push $REPO_URL/ubi10:10.2
bento:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - bento/**/*
  needs:
    - job: ubi10
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/bento --network=host ./bento/
    buildah push $REPO_URL/bento
golang:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - golang/**/*
  needs:
    - job: ubi10
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/golang --network=host ./golang/
    buildah push $REPO_URL/golang
caddy:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - caddy/**/*
  needs:
    - job: golang
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/caddy --network=host ./caddy/
    buildah push $REPO_URL/caddy
python:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - python/**/*
  needs:
    - job: ubi10
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/python --network=host ./python/
    buildah push $REPO_URL/python
ansible:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - ansible/**/*
  needs:
    - job: ubi10
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/ansible --network=host ./ansible/
    buildah push $REPO_URL/ansible
