---
include:
  - local: ansible/.gitlab-ci.yaml
  - local: bento/.gitlab-ci.yaml
  - local: bootstrap/.gitlab-ci.yaml
  - local: caddy/.gitlab-ci.yaml
  - local: garage/.gitlab-ci.yaml
  - local: golang/.gitlab-ci.yaml
  - local: jellyfin/.gitlab-ci.yaml
  - local: python/.gitlab-ci.yaml
  - local: rabbitmq/.gitlab-ci.yaml
  - local: rclone/.gitlab-ci.yaml
  - local: rust/.gitlab-ci.yaml
  - local: rustfs/.gitlab-ci.yaml
  - local: tinyproxy/.gitlab-ci.yaml
  - local: ubi10/.gitlab-ci.yaml
  - local: ubi10-minimal/.gitlab-ci.yaml
  - local: vsftpd/.gitlab-ci.yaml
  - local: yt-dlp/.gitlab-ci.yaml
  - local: zensical/.gitlab-ci.yaml
