---
include:
  - local: bootstrap/.gitlab-ci.yaml
  - local: ubi10/.gitlab-ci.yaml
  - local: golang/.gitlab-ci.yaml
  - local: caddy/.gitlab-ci.yaml
  - local: python/.gitlab-ci.yaml
  - local: ansible/.gitlab-ci.yaml
  - local: zensical/.gitlab-ci.yaml
  - local: yt-dlp/.gitlab-ci.yaml
  - local: bento/.gitlab-ci.yaml
  - local: jellyfin/.gitlab-ci.yaml
  - local: garage/.gitlab-ci.yaml
