---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          knot
          knot-dnssecutils
          knot-module-dnstap
          knot-utils
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item.dest }}"
        state: "{{ item.state }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - dest: "/usr/share/knot"
          state: "directory"
          mode: "0755"
        - dest: "/usr/share/knot/knot.conf"
          state: "touch"
          mode: "0644"
        - dest: "/etc/tmpfiles.d/knot.conf"
          state: "touch"
          mode: "0644"
    - ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ container_path }}{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - src: "{{ container_path }}/etc/knot/knot.conf"
          dest: "/usr/share/knot/knot.conf"
          mode: "0644"
        - src: "etc/tmpfiles.d/knot.conf"
          dest: "/etc/tmpfiles.d/knot.conf"
          mode: "0644"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl enable knot.service"
        - "buildah config --volume /etc/knot {{ container_uuid }}"
        - "buildah config --volume /var/lib/knot {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
