---
- ansible.builtin.tempfile:
    state: "directory"
  register: "result_tempfile"
- ansible.builtin.set_fact:
    container_uuid: "{{ lookup('ansible.builtin.file', '/proc/sys/kernel/random/uuid') }}"
- ansible.builtin.command:
    cmd: "buildah from --quiet --pull=false --name={{ container_uuid }} {{ registry_host }}/{% if bootstrap %}bootstrap/{% endif %}{{ base_name }}:{{ base_tag }}"
- ansible.builtin.command:
    cmd: "buildah mount {{ container_uuid }}"
  register: "result_command"
- ansible.builtin.set_fact:
    container_path: "{{ result_command.stdout }}"
- ansible.builtin.file:
    dest: "{{ container_path }}{{ item }}"
    state: "touch"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - "/etc/yum.repos.d/redhat.repo"
  when: "bootstrap and base_name != 'scratch' and image_os == 'rhel"
- ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ container_path }}{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - "/etc/yum.repos.d/redhat.repo"
  when: "bootstrap and base_name != 'scratch' and image_os == 'rhel"
