---
- ansible.builtin.tempfile:
    state: "directory"
    #path: "{{ container_path }}/tmp"
  register: "result_tempfile"
- ansible.builtin.set_fact:
    container_uuid: "{{ lookup('ansible.builtin.file', '/proc/sys/kernel/random/uuid') }}"
- ansible.builtin.command:
    cmd: "buildah from --quiet --pull=false --name={{ container_uuid }} {{ registry_host }}/{% if bootstrap %}bootstrap/{% endif %}{{ base_name }}:{{ base_tag }}"
- ansible.builtin.command:
    cmd: "buildah mount {{ container_uuid }}"
  register: "result_command"
- ansible.builtin.set_fact:
    container_path: "{{ result_command.stdout }}"
