ARG PROJ_IMAGES_REPO

FROM ${PROJ_IMAGES_REPO}/ubi10-minimal:latest

ARG PROJ_RAW_REPO
ARG REPO_USERNAME
ARG REPO_PASSWORD

COPY rootfs/ /

RUN <<EOF
    curl -u ${REPO_USERNAME}:${REPO_PASSWORD} -Lo /usr/bin/caddy https://${PROJ_RAW_REPO}/caddy/2.11.4/caddy_linux_amd64_custom
    chmod 0755 /usr/bin/caddy
EOF

VOLUME /etc/caddy
