FROM repo.skarbek.name/h-con-infra/golang:latest AS builder

WORKDIR /root/

RUN <<EOT
    curl -Lo xcaddy.tar.gz https://github.com/caddyserver/xcaddy/releases/download/v0.4.5/xcaddy_0.4.5_linux_amd64.tar.gz
    tar -xf xcaddy.tar.gz
    chmod 0755 xcaddy
    ./xcaddy build  v2.11.3 \
    --with github.com/caddy-dns/route53@v1.6.2 \
    --with github.com/caddy-dns/cloudflare@v0.2.4
EOT

FROM repo.skarbek.name/h-con-infra/ubi10:10.2

COPY --from=builder /root/caddy /usr/local/bin/caddy

COPY rootfs/ /

CMD ["/usr/bin/dinit", "--container"]

VOLUME /etc/caddy
