---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - "/etc/yum.repos.d/pgdg-redhat-all.repo"
        - "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG"
#      when: "proxy_repos"
    - ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ container_path }}{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - src: "repos/pgdg-redhat-all.repo"
          dest: "/etc/yum.repos.d/pgdg-redhat-all.repo"
        - src: "rpm-gpg/RPM-GPG-KEY-PGDG"
          dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG"
#      when: "proxy_repos"
    - ansible.builtin.command:
        cmd: "rpm --root {{ container_path }} --import {{ container_path }}/etc/pki/rpm-gpg/{{ item }}"
      loop:
        - "RPM-GPG-KEY-PGDG"
#      when: "proxy_repos"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          postgresql17-server
          postgresql17-contrib
          pg_qualstats_17
          pg_stat_kcache_17
          pg_wait_sampling_17
          pg_track_settings_17
          hypopg_17
          pgvector_17
#          pg_auto_failover_17
#          citus_17
    - ansible.posix.synchronize:
        src: rootfs/
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.builtin.command:
        cmd: "buildah run --network none {{ container_uuid }} systemctl enable postgresql-17.service"
    - ansible.builtin.command:
        cmd: "buildah config --volume /var/lib/pgsql/17/data {{ container_uuid }}"
    - ansible.builtin.command:
        cmd: "buildah config --volume /var/lib/pgsql/17/backups {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
