default:
  tags:
    - buildah

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

stages:
  - sync
  - download

sync-mirror:
  stage: sync
  script:
    - ./mirror.sh

download-artefacts:
  stage: download
  script:
    - ./downloads.sh
  needs:
    - sync-mirror
