---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: marcin
      zfs_pool: b51d7037-4cc1-4ad9-9e50-b533fd87b24e
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
    env: lcl
