---
- hosts: all
  gather_facts: no
  tasks:
    - name: Crete minio
      ansible.builtin.import_role:
        name: minio
    - name: Crete minio-console
      ansible.builtin.import_role:
        name: minio-console
