---
- hosts: local
  gather_facts: no
  tasks:
    - ansible.builtin.file:
        dest: "{{ playbook_dir }}/zfs-el8"
        state: directory
    - containers.podman.podman_container:
        name: builder-el8
        state: started
        image: "docker.io/almalinux/8-base:8.5"
        command: "sleep 60m"
        volume:
          - "{{ playbook_dir }}/zfs-el8:/root/zfs:z"
- hosts: builder-el8
  gather_facts: no
  vars:
    version_kernel: "4.18.0-348.el8"
  tasks:
    - ansible.builtin.dnf:
        name: "*"
        state: latest
    - ansible.builtin.dnf:
        name: epel-release
        state: present
    - ansible.builtin.dnf:
        name:
          - autoconf
          - automake
          - dkms
          - elfutils-libelf-devel
          - gcc
          - "kernel-abi-stablelists-{{ version_kernel }}"
          - "kernel-devel-{{ version_kernel }}"
          - "kernel-headers-{{ version_kernel }}"
          - kernel-rpm-macros
          - kmod
          - libaio-devel
          - libattr-devel
          - libblkid-devel
          - libffi-devel
          - libtirpc-devel
          - libtool
          - libudev-devel
          - libuuid-devel
          - make
          - ncompress
          - openssl-devel
          - python3
          - python3-cffi
          - python3-devel
          - python3-packaging
          - python3-setuptools
          - rpm-build
          - zlib-devel
        state: present
        enablerepo: powertools
    - ansible.builtin.user:
        name: mockbuild
    - ansible.builtin.get_url:
        url: "https://github.com/openzfs/zfs/releases/download/zfs-{{ version_zfs }}/zfs-{{ version_zfs }}.tar.gz"
        dest: "/home/mockbuild/zfs-{{ version_zfs }}.tar.gz"
      become: yes
      become_user: mockbuild
    - ansible.builtin.unarchive:
        src: "/home/mockbuild/zfs-{{ version_zfs }}.tar.gz"
        dest: "/home/mockbuild"
        remote_src: yes
      become: yes
      become_user: mockbuild
    - ansible.builtin.command:
        cmd: ./configure --with-spec=redhat
        chdir: "/home/mockbuild/zfs-{{ version_zfs }}"
      become: yes
      become_user: mockbuild
    - ansible.builtin.command:
        cmd: make -j1 rpm-utils
        chdir: "/home/mockbuild/zfs-{{ version_zfs }}"
      become: yes
      become_user: mockbuild
    - ansible.builtin.command:
        cmd: make -j1 rpm-kmod
        chdir: "/home/mockbuild/zfs-{{ version_zfs }}"
      become: yes
      become_user: mockbuild
    - ansible.builtin.find:
        paths: "/home/mockbuild/zfs-{{ version_zfs }}/"
        patterns: "*.rpm"
        file_type: file
        recurse: no
      register: rpms
    - ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /root/zfs/
        remote_src: yes
      loop: "{{ rpms.files }}"
- hosts: local
  gather_facts: no
  tasks:
    - containers.podman.podman_container:
        name: builder-el8
        state: absent
