---
- name: Create mesh config
  ansible.builtin.template:
    src: mesh.yaml.j2
    dest: "/var/lib/volumes/storage/{{ kuma_env + '-' + service_name + '-' + deployment_id + '-app' + '/etc/kuma'|replace('/', '-') }}/_data/{{ mesh_env }}-mesh.yaml"
    owner: root
    group: root
    mode: "0644"
    seuser: system_u
    serole: object_r
    setype: container_file_t
    selevel: s0
- name: Create traffic-log config
  ansible.builtin.template:
    src: traffic-log.yaml.j2
    dest: "/var/lib/volumes/storage/{{ kuma_env + '-' + service_name + '-' + deployment_id + '-app' + '/etc/kuma'|replace('/', '-') }}/_data/{{ mesh_env }}-traffic-log.yaml"
    owner: root
    group: root
    mode: "0644"
    seuser: system_u
    serole: object_r
    setype: container_file_t
    selevel: s0
- name: Configure mesh in kuma
  ansible.builtin.command:
    cmd: "podman exec {{ kuma_env + '-' + service_name + '-' + deployment_id + '-app' }} kumactl apply -f /etc/kuma/{{ mesh_env }}-mesh.yaml"
- name: Configure traffic-log in kuma
  ansible.builtin.command:
    cmd: "podman exec {{ kuma_env + '-' + service_name + '-' + deployment_id + '-app' }} kumactl apply -f /etc/kuma/{{ mesh_env }}-traffic-log.yaml"
