#User tinyproxy
#Group tinyproxy
Listen 0.0.0.0
Port 8080
Timeout 600
Allow 0.0.0.0/0
MaxClients 100

Upstream http ${PROXY_USERNAME}:${PROXY_PASSWORD}@${PROXY_HOST}

#LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info
DefaultErrorFile "/usr/share/tinyproxy/default.html"
ViaProxyName "tinyproxy"
