---
- name: Generate deployment id
  ansible.builtin.include_role:
    name: pod_id
    tasks_from: get
- name: Deploy kuma-cp pod
  ansible.builtin.include_role:
    name: podman_pod
    tasks_from: present
  vars:
    pod_name: "{{ future_pod_name }}"
- name: Deploy kuma-cp container
  ansible.builtin.include_role:
    name: podman_container
    tasks_from: present
  vars:
    container_name: "{{ future_app_container_name }}"
    container_pod: "{{ future_pod_name }}"
    container_image: "registry.lab.skarbek.name/bootstrap/kuma-cp:latest"
    container_catatonit: false
    container_volumes:
      - container_volume_mountpoint: /etc/kuma
        container_volume_type: zfs
      - container_volume_mountpoint: /var/log/kuma
        container_volume_type: zfs
      - container_volume_mountpoint: /var/log/journal
        container_volume_type: zfs
- name: Start kuma-cp pod
  ansible.builtin.include_role:
    name: podman_pod
    tasks_from: started
  vars:
    pod_name: "{{ future_pod_name }}"
- name: Start kuma-cp container
  ansible.builtin.include_role:
    name: podman_container
    tasks_from: started
  vars:
    container_name: "{{ future_app_container_name }}"
