---
- name: Generate token
  ansible.builtin.command:
    cmd: "podman exec {{ env + '-kuma-' + lookup('consul_kv', env + '/defaults/kuma_id', host=consul_host) + '-app' }} kumactl generate dataplane-token --mesh={{ env }} --name={{ env + '-' + service + '-' + future_pod }}"
  register: mesh_token
- name: Create mesh volumes
  ansible.builtin.include_role:
    name: podman-volume
  vars:
    #service: "{{ service }}"
    container_type: mesh
    volume_mountpoint: "{{ item }}"
  loop:
    - /etc/kuma
    - /var/log/kuma

- name: Create dataplane config
  ansible.builtin.template:
    src: dataplane.yaml.j2
    dest: "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-mesh' + '/etc/kuma'|replace('/', '-') }}/_data/dataplane.yaml"

- name: Create mesh secret
  ansible.builtin.import_role:
    name: podman-secret
  vars:
    #service: "{{ service }}"
    container_type: mesh
    secret_name: token
    secret_data: "{{ mesh_token.stdout }}"

- name: Create mesh container
  containers.podman.podman_container:
    name: "{{ env + '-' + service + '-' + future_pod + '-mesh' }}"
    pod: "{{ env + '-' + service + '-' + future_pod }}"
    init: yes
    image: "{{ lookup('consul_kv', env + '/defaults/registry_url', host=consul_host) + '/bootstrap/base/kuma-dp:latest' }}"
    command:
      - /usr/local/bin/kuma-dp
      - run
      - --log-output-path=/var/log/kuma/kuma-dp.log
      - --cp-address=https://{{ lookup('consul_kv', env + '/defaults/kuma_ip', host=consul_host) }}:5678/
      - --dns-enabled=false
      - --dataplane-file=/etc/kuma/dataplane.yaml
      - --dataplane-token-file=/run/secrets/kuma-token
      - --config-dir=/run/kuma/envoy/
      - --dns-server-config-dir=/run/kuma/coredns/
    mount:
      - type=tmpfs,destination=/run/kuma
    volume:
      - "{{ env + '-' + service + '-' + future_pod + '-mesh' + '/etc/kuma'|replace('/', '-') }}:/etc/kuma:z"
      - "{{ env + '-' + service + '-' + future_pod + '-mesh' + '/var/log/kuma'|replace('/', '-') }}:/var/log/kuma:z"
    secrets:
      - "{{ env + '-' + service + '-' + future_pod + '-mesh-token' }},type=mount,target=kuma-token"
      - "{{ env + '-kuma-config' }},type=mount,target=kuma-config"
