---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item.dest }}"
        state: "{{ item.state }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - dest: "/etc/sysusers.d"
          state: "directory"
          mode: "0755"
        - dest: "/usr/share/prometheus"
          state: "directory"
          mode: "0755"
        - dest: "/etc/systemd/system/prometheus.service"
          state: "touch"
          mode: "0644"
        - dest: "/etc/sysusers.d/prometheus.conf"
          state: "touch"
          mode: "0644"
        - dest: "/etc/tmpfiles.d/prometheus.conf"
          state: "touch"
          mode: "0644"
        - dest: "/usr/bin/prometheus"
          state: "touch"
          mode: "0755"
        - dest: "/usr/bin/promtool"
          state: "touch"
          mode: "0755"
        - dest: "/usr/share/prometheus/prometheus-local-config.yaml"
          state: "touch"
          mode: "0644"
    - ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: "{{ result_tempfile.path }}"
        remote_src: true
      loop:
        - "{{ prometheus_public_url }}"
      when: "not use_repository"
    - ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: "{{ result_tempfile.path }}"
        remote_src: true
      loop:
        - "{{ prometheus_proxy_url }}"
      when: "use_repository"
    - ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ container_path }}{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - src: "etc/systemd/system/prometheus.service"
          dest: "/etc/systemd/system/prometheus.service"
          mode: "0644"
        - src: "etc/sysusers.d/prometheus.conf"
          dest: "/etc/sysusers.d/prometheus.conf"
          mode: "0644"
        - src: "etc/tmpfiles.d/prometheus.conf"
          dest: "/etc/tmpfiles.d/prometheus.conf"
          mode: "0644"
        - src: "{{ result_tempfile.path }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
          dest: "/usr/share/prometheus/prometheus-local-config.yaml"
          mode: "0644"
        - src: "{{ result_tempfile.path }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
          dest: "/usr/bin/prometheus"
          mode: "0755"
        - src: "{{ result_tempfile.path }}/prometheus-{{ prometheus_version }}.linux-amd64/promtool"
          dest: "/usr/bin/promtool"
          mode: "0755"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl enable prometheus.service"
        - "buildah config --volume /etc/prometheus {{ container_uuid }}"
        - "buildah config --volume /var/lib/prometheus {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
