---
ubi10-minimal:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - ubi10-minimal/**/*
  needs:
    - job: bootstrap
      optional: true
  image: $REPO_URL/buildah:latest
  script: |-
    set -euxo pipefail
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/ubi10-minimal:10.2 --network=host ./ubi10-minimal/ \
    --build-arg PROJ_YUM_REPO=${PROJ_YUM_REPO} \
    --build-arg REPO_USERNAME=${REPO_USERNAME} \
    --build-arg REPO_PASSWORD=${REPO_PASSWORD}
    buildah push $REPO_URL/ubi10-minimal:10.2
