FROM repo.skarbek.name/p-con-docker/redhat/ubi10-minimal:10.2

COPY rootfs/ /

RUN <<EOF
    rm /etc/yum.repos.d/ubi.repo
    microdnf -y install catatonit dinit gettext-envsubst
    microdnf clean all
EOF

ENTRYPOINT ["/usr/libexec/catatonit/catatonit", "--"]
