ARG BASE_IMAGES_REPO

FROM ${BASE_IMAGES_REPO}/ubi10-minimal:latest

ARG PROJ_YUM_REPO
ARG REPO_USERNAME
ARG REPO_PASSWORD

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    rm /etc/yum.repos.d/ubi.repo
    microdnf -y update
    microdnf -y install catatonit gettext-envsubst nmap-ncat
    envsubst < /etc/yum.repos.d/proj.tmpl > /etc/yum.repos.d/proj.repo
    rm /etc/yum.repos.d/proj.tmpl
    microdnf -y install dinit
    microdnf clean all
EOF

ENV DINIT_SOCKET_PATH=/tmp/.dinitctl

ENTRYPOINT ["/usr/libexec/catatonit/catatonit", "--"]

CMD ["/usr/bin/dinit", "-u", "-p", "/tmp/.dinitctl", "-d", "/etc/dinit.d"]
