ARG PROJ_IMAGES_REPO

FROM ${PROJ_IMAGES_REPO}/ubi10-minimal:latest

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    microdnf -y install tinyproxy
    microdnf clean all
    rm /etc/tinyproxy/tinyproxy.conf
EOF

VOLUME /etc/tinyproxy
