ARG BASE_IMAGES_REPO

FROM ${BASE_IMAGES_REPO}/ubi10-minimal:latest

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    microdnf -y install tinyproxy
    microdnf clean all
    mkdir -p /usr/share/tinyproxy
    mv /etc/tinyproxy/tinyproxy.conf /usr/share/tinyproxy/
EOF

VOLUME /etc/tinyproxy
