---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
#    - ansible.builtin.dnf:
#        name:
#          - "curl"
#          - "dmenu"
#          - "findutils"
#          - "firefox"
#          - "fish"
#          - "hostname"
#          - "i3"
#          - "i3status"
#          - "iproute"
#          - "iputils"
#          - "nano"
#          - "openssh-clients"
#          - "passwd"
#          - "rxvt-unicode"
#          - "sudo"
#          - "vim-enhanced"
#          - "vim-minimal"
#          - "xorgxrdp"
#          - "xrdp"
#        conf_file: "{{ container_path }}/etc/dnf/dnf.conf"
#        install_weak_deps: false
#        state: "latest"
#        installroot: "{{ container_path }}"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          curl
          dmenu
          findutils
          firefox
          fish
          hostname
          i3
          i3status
          iproute
          iputils
          nano
          openssh-clients
          passwd
          rxvt-unicode
          sudo
          vim-enhanced
          vim-minimal
          xorgxrdp
          xrdp
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl unmask systemd-logind.service"
        - "buildah run --network none {{ container_uuid }} systemctl set-default graphical.target"
        - "buildah run --network none {{ container_uuid }} systemctl mask power-profiles-daemon.service upower.service"
        - "buildah run --network none {{ container_uuid }} systemctl enable xrdp.service"
        - "rm -vf {{ container_path }}/usr/libexec/xrdp/startwm.sh"
    - ansible.builtin.command:
        cmd: "sed -i 's/session[ \t]*required[ \t]*pam_loginuid.so/#session    required     pam_loginuid.so/' {{ container_path }}/etc/pam.d/{{ item }}"
      loop:
        - "sshd"
        - "remote"
        - "login"
        - "systemd-user"
    - ansible.posix.synchronize:
        src: rootfs/
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
