---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - "/usr/lib/apache-jmeter"
        - /usr/share/doc/apache-jmeter
        - /usr/share/licenses/apache-jmeter
    - ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ result_tempfile.path }}/{{ item.dest }}"
        force: true
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - url: "{{ jmeter_public_url }}"
          dest: "apache-jmeter-{{ jmeter_version }}.tgz"
        - url: "{{ kloadgen_public_url }}"
          dest: "kloadgen-{{ kloadgen_version }}.jar"
      when: "not use_repository"
    - ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ result_tempfile.path }}/{{ item.dest }}"
        force: true
        username: "{{ repository_username }}"
        password: "{{ repository_password }}"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - url: "{{ jmeter_proxy_url }}"
          dest: "apache-jmeter-{{ jmeter_version }}.tgz"
        - url: "{{ kloadgen_proxy_url }}"
          dest: "kloadgen-{{ kloadgen_version }}.jar"
      when: "use_repository"
    - ansible.builtin.unarchive:
        src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}.tgz"
        dest: "{{ result_tempfile.path }}"
        #remote_src: true
    - ansible.posix.synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        archive: true
      loop:
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/README.md"
          dest: "{{ container_path }}/usr/share/doc/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/NOTICE"
          dest: "{{ container_path }}/usr/share/doc/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/docs"
          dest: "{{ container_path }}/usr/share/doc/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/printable_docs"
          dest: "{{ container_path }}/usr/share/doc/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/LICENSE"
          dest: "{{ container_path }}/usr/share/licenses/apache-jmeter/"  
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/licenses/"
          dest: "{{ container_path }}/usr/share/licenses/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/bin"
          dest: "{{ container_path }}/usr/lib/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/extras"
          dest: "{{ container_path }}/usr/lib/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/apache-jmeter-{{ jmeter_version }}/lib"
          dest: "{{ container_path }}/usr/lib/apache-jmeter/"
        - src: "{{ result_tempfile.path }}/kloadgen-{{ kloadgen_version }}.jar"
          dest: "{{ container_path }}/usr/lib/apache-jmeter/lib/ext/"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
