---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.x86_64.rpm
      when: "not use_repository"
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          grafana
      when: "use_repository"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - "/usr/share/grafana/etc"
        - "/usr/share/grafana/plugins"
    - ansible.posix.synchronize:
        src: "{{ container_path }}{{ item.src }}"
        dest: "{{ container_path }}{{ item.dest }}"
        archive: true
      loop:
        - src: "/etc/grafana/"
          dest: "/usr/share/grafana/etc/"
      loop_control:
        label: "{{ item.dest }}"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "absent"
      loop:
        - "/etc/grafana"
        - "/etc/init.d/grafana-server"
    - ansible.posix.synchronize:
        src: rootfs/
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl enable grafana-server.service"
        - "buildah config --volume /etc/grafana {{ container_uuid }}"
        - "buildah config --volume /var/lib/grafana {{ container_uuid }}"
        - "buildah config --volume /var/log/grafana {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
