FROM repo.skarbek.name/p-con-docker/redhat/ubi10:10.2

COPY rootfs/ /

RUN <<EOF
    rm /etc/yum.repos.d/ubi.repo
    dnf -y install catatonit dinit gettext-envsubst
    dnf clean all
EOF

ENTRYPOINT ["/usr/libexec/catatonit/catatonit", "--"]
