FROM ghcr.io/mskarbek/containers/init:10.1

COPY rootfs/ /

RUN dnf -y install erlang rabbitmq-server-4.2.3-1.el8.noarch;\
 dnf clean all;\
 ln -s\
 /usr/lib/systemd/system/rabbitmq-server.service\
 /etc/systemd/system/multi-user.target.wants/rabbitmq-server.service

VOLUME /etc/rabbitmq
VOLUME /var/lib/rabbitmq
VOLUME /var/log/rabbitmq
