ARG PROJ_IMAGES_REPO

FROM ${PROJ_IMAGES_REPO}/ubi10-minimal:latest

COPY rootfs/ /

RUN <<EOF
    dnf -y install erlang rabbitmq-server
    dnf clean all
EOF

VOLUME /etc/rabbitmq
VOLUME /var/lib/rabbitmq
