ARG PROJ_IMAGES_REPO

FROM ${PROJ_IMAGES_REPO}/ubi10-minimal:latest

COPY rootfs/ /

RUN <<EOF
    set -euxo pipefail
    dnf -y install erlang rabbitmq-server
    dnf clean all
EOF

ENV HOME=/var/lib/rabbitmq

VOLUME /etc/rabbitmq
VOLUME /var/lib/rabbitmq
VOLUME /var/log/rabbitmq
