---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
#    - ansible.builtin.dnf:
#        name:
#          - "clang"
#          - "curl"
#          - "file"
#          - "git-core"
#          - "mesa-libGLU"
#          - "unzip"
#          - "which"
#          - "xz"
#          - "zip"
#        conf_file: "{{ container_path }}/etc/dnf/dnf.conf"
#        install_weak_deps: false
#        state: "latest"
#        installroot: "{{ container_path }}"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          clang
          curl
          file
          git-core
          mesa-libGLU
          unzip
          which
          xz
          zip
    - ansible.builtin.unarchive:
        src: "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ flutter_version }}-stable.tar.xz"
        dest: "{{ container_path }}/opt"
        remote_src: true
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} useradd --comment 'Flutter' --create-home --shell /usr/bin/bash flutter"
        - "buildah run --network none {{ container_uuid }} chown -R flutter:flutter /opt/flutter"
        - "buildah config --user flutter {{ container_uuid }}"
        - "buildah config --workingdir /home/flutter {{ container_uuid }}"
        - "buildah config --env 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/flutter/bin' {{ container_uuid }}"
        - "buildah run --network none {{ container_uuid }} flutter config --no-analytics"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
