---
- ansible.builtin.file:
    dest: "{{ container_path }}{{ item }}"
    state: "touch"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - "/etc/dnf/dnf.conf"
    - "/etc/yum.repos.d/redhat.repo"
    - "/etc/yum.repos.d/epel.repo"
    - "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
    - "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9"
- ansible.builtin.template:
    src: "dnf.conf.j2"
    dest: "{{ container_path }}/etc/dnf/dnf.conf"
    owner: "root"
    group: "root"
    mode: "0644"
- ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ container_path }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - src: "repos/redhat.repo"
      dest: "/etc/yum.repos.d/redhat.repo"
    - src: "repos/epel.repo"
      dest: "/etc/yum.repos.d/epel.repo"
    - src: "rpm-gpg/RPM-GPG-KEY-redhat-release"
      dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
    - src: "rpm-gpg/RPM-GPG-KEY-EPEL-9"
      dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9"
#- ansible.builtin.dnf:
#    name:
#      - "glibc-minimal-langpack"
#      - "coreutils-single"
#    conf_file: "{{ container_path }}/etc/dnf/dnf.conf"
#    disablerepo: "*"
#    enablerepo: "rhel-9-for-x86_64-baseos-rpms"
#    disable_plugin:
#      - "subscription-manager"
#    install_weak_deps: false
#    releasever: 9
#    state: "latest"
#    disable_gpg_check: true
#    installroot: "{{ container_path }}"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
- ansible.builtin.command:
    cmd: >
      dnf
      --quiet
      --assumeyes
      --disablerepo="*"
      --enablerepo="rhel-9-for-x86_64-baseos-rpms"
      --disableplugin="subscription-manager"
      --nogpgcheck
      --releasever=9
      --config={{ container_path }}/etc/dnf/dnf.conf
      --installroot={{ container_path }}
      install
      glibc-minimal-langpack
      coreutils-single
- ansible.builtin.command:
    cmd: "rpm --root {{ container_path }} --import {{ container_path }}/etc/pki/rpm-gpg/{{ item }}"
  loop:
    - "RPM-GPG-KEY-redhat-release"
    #- "RPM-GPG-KEY-redhat-beta"
    - "RPM-GPG-KEY-EPEL-9"
#- ansible.builtin.dnf:
#    name:
#      - "ca-certificates"
#    conf_file: "{{ container_path }}/etc/dnf/dnf.conf"
#    install_weak_deps: false
#    state: "latest"
#    installroot: "{{ container_path }}"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
- ansible.builtin.command:
    cmd: >
      dnf
      --quiet
      --assumeyes
      --disableplugin="subscription-manager"
      --config={{ container_path }}/etc/dnf/dnf.conf
      --installroot={{ container_path }}
      install
      ca-certificates
