---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - "/usr/local/bin/consul"
    - ansible.builtin.get_url:
        url: "{{ consul_public_url }}"
        dest: "{{ result_tempfile.path }}/consul_{{ consul_version }}_linux_amd64.zip"
        force: true
        owner: "root"
        group: "root"
        mode: "0644"
      when: "not use_repository"
    - ansible.builtin.get_url:
        url: "{{ consul_proxy_url }}"
        dest: "{{ result_tempfile.path }}/consul_{{ consul_version }}_linux_amd64.zip"
        force: true
        username: "{{ repository_username }}"
        password: "{{ repository_password }}"
        owner: "root"
        group: "root"
        mode: "0644"
      when: "use_repository"
    - ansible.builtin.unarchive:
        src: "{{ result_tempfile.path }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "{{ result_tempfile.path }}/"
        remote_src: true
    - ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ container_path }}{{ item.dest }}"
        force: true
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - dest: "/usr/local/bin/consul"
          src: "{{ result_tempfile.path }}/consul"
    - ansible.posix.synchronize:
        src: rootfs/
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl enable consul.service"
        - "buildah config --volume /etc/consul.d {{ container_uuid }}"
        - "buildah config --volume /var/lib/consul {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
