---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.file:
        dest: "{{ container_path }}/usr/local/bin/consul"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "{{ result_tempfile.path }}"
        remote_src: true
    - ansible.posix.synchronize:
        src: rootfs/
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.builtin.command:
        cmd: >
          buildah run --network none {{ container_uuid }} systemctl enable
          consul.service
    - ansible.builtin.command:
        cmd: "buildah config --volume /etc/consul.d {{ container_uuid }}"
    - ansible.builtin.command:
        cmd: "buildah config --volume /var/lib/consul {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
