FROM quay.io/centos/centos:stream8

COPY --chown=root:root ./etc /etc

RUN dnf clean all\
 && dnf config-manager --set-enabled powertools\
 && dnf config-manager --set-enabled ha\
 && dnf -y update\
 && dnf -y install buildah skopeo rsync unzip systemd procps-ng --exclude=container-selinux\
 && curl -L -o /tmp/awscli-exe-linux-x86_64.zip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\
 && cd /tmp\
 && unzip awscli-exe-linux-x86_64.zip\
 && cd aws\
 && bash -ex ./install\
 && cd /root\
 && rm -rvf /tmp/aws\
 && rm -vf /tmp/awscli-exe-linux-x86_64.zip\
 && systemctl set-default multi-user.target\
 && systemctl mask\
 console-getty.service\
 dev-hugepages.mount\
 dnf-makecache.timer\
 getty.target\
 local-fs.target\
 remote-fs.target\
 swap.target\
 veritysetup.target\
 kdump.service\
 sys-fs-fuse-connections.mount\
 systemd-ask-password-console.path\
 systemd-ask-password-wall.path\
 systemd-homed.service\
 systemd-hostnamed.service\
 systemd-logind.service\
 systemd-machine-id-commit.service\
 systemd-random-seed.service\
 systemd-remount-fs.service\
 systemd-resolved.service\
 systemd-udev-trigger.service\
 systemd-udevd.service

STOPSIGNAL SIGRTMIN+3
CMD [ "/usr/sbin/init" ]
