FROM ghcr.io/mskarbek/rust:1.88.0 AS builder

WORKDIR /root/

RUN dnf -y install openssl-devel;\
 dnf clean all;\
 curl -Lo pgdog.tar.gz https://github.com/pgdogdev/pgdog/archive/refs/tags/v0.1.28.tar.gz;\
 mkdir pgdog;\
 cd pgdog;\
 tar -xf ../pgdog.tar.gz --strip-components=1;\
 cargo build --release


FROM ghcr.io/mskarbek/containers/init:10.1

COPY --from=builder /root/pgdog/target/release/pgdog /usr/local/bin/pgdog

COPY rootfs/ /

RUN ln -s\
 /etc/systemd/system/pgdog.service\
 /etc/systemd/system/multi-user.target.wants/pgdog.service

VOLUME /etc/pgdog
