FROM ghcr.io/mskarbek/inits:10.1 AS builder

WORKDIR /root/

RUN dnf -y install openssl-devel clang-devel mold;\
 dnf clean all;\
 curl -Lo rustup-init.sh https://sh.rustup.rs;\
 sh rustup-init.sh -qy;\
 curl -Lo pgdog.tar.gz https://github.com/pgdogdev/pgdog/archive/refs/tags/v0.1.32.tar.gz;\
 mkdir pgdog;\
 cd pgdog;\
 tar -xf ../pgdog.tar.gz --strip-components=1;\
 cargo build --release


FROM ghcr.io/mskarbek/inits:10.1

COPY --from=builder /root/pgdog/target/release/pgdog /usr/local/bin/pgdog

COPY rootfs/ /

RUN systemctl enable pgdog.service

VOLUME /etc/pgdog
