---
- name: Get keycloak pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: get

- name: Stop current keycloak pod
  containers.podman.podman_pod:
    name: "{{ env + '-keycloak-' + current_pod }}"
    state: stopped
  when: current_pod != []
- name: Stop failed keycloak pod
  containers.podman.podman_pod:
    name: "{{ env + '-keycloak-' + failed_pod }}"
    state: stopped
  when: failed_pod != []

- name: Create keycloak volumes
  ansible.builtin.include_role:
    name: podman-volume
  vars:
    service: keycloak
    container_type: app
    volume_mountpoint: "{{ item }}"
  loop:
    - /usr/lib/keycloak/standalone/data
    - /usr/lib/keycloak/standalone/log
    - /usr/lib/keycloak/standalone/configuration

- name: Create keycloak config
  ansible.builtin.copy:
    src: standalone.xml
    dest: "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-app' + '/usr/lib/keycloak/standalone/configuration'|replace('/', '-') }}/_data/standalone.xml"

- name: Create keycloak pod
  ansible.builtin.import_role:
    name: podman-pod
  vars:
    service: keycloak
    pod_publish:
- name: Create keycloak container
  ansible.builtin.import_role:
    name: podman-container
  vars:
    service: keycloak
    container_image: "{{ lookup('consul_kv', env + '/defaults/registry_url', host=consul_host) + '/bootstrap/keycloak:latest' }}"
    container_type: app
    container_volumes:
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/usr/lib/keycloak/standalone/data'|replace('/', '-') }}:/usr/lib/keycloak/standalone/data:z"
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/usr/lib/keycloak/standalone/log'|replace('/', '-') }}:/usr/lib/keycloak/standalone/log:z"
      - "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-app' + '/usr/lib/keycloak/standalone/configuration'|replace('/', '-') }}/_data/standalone.xml:/usr/lib/keycloak/standalone/configuration/standalone.xml:z"
    container_secrets:

- name: Create keycloak mesh
  ansible.builtin.import_role:
    name: mesh
  vars:
    service: keycloak
    mesh_gateway:
    mesh_inbound:
      - service: keycloak-web
        protocol: http
        address: "127.0.0.1"
        port: "8080"
      - service: keycloak-mgmt
        protocol: http
        address: "127.0.0.1"
        port: "9090"
    mesh_outbound:
      - service: postgres
        port: "12001"

- name: Set keycloak pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: set
