---
- name: Get pods ids
  ansible.builtin.set_fact:
    past_pod: "{{ lookup('consul_kv', env + '/services/' + service + '/past_pod', host=consul_host) }}"
    current_pod: "{{ lookup('consul_kv', env + '/services/' + service + '/current_pod', host=consul_host) }}"
    failed_pod: "{{ lookup('consul_kv', env + '/services/' + service + '/future_pod', host=consul_host) }}"
- name: Set remote future pod id
  community.general.consul_kv:
    host: "{{ consul_host }}"
    key: "{{ env + '/services/' + service + '/future_pod' }}"
    value: "{{ lookup('pipe', 'date +%y%m%d%H%M') }}"
- name: Set local future pod id
  ansible.builtin.set_fact:
    future_pod: "{{ lookup('consul_kv', env + '/services/' + service + '/future_pod', host=consul_host) }}"
