---
- name: Set remote past id
  community.general.consul_kv:
    host: "{{ consul_host }}"
    key: "{{ env + '/services/' + service_name + '/past_id' }}"
    value: "{{ current_id }}"
  when: current_id != []
- name: Set remote current id
  community.general.consul_kv:
    host: "{{ consul_host }}"
    key: "{{ env + '/services/' + service_name + '/current_id' }}"
    value: "{{ future_id }}"
- name: Clean remote future id
  community.general.consul_kv:
    host: "{{ consul_host }}"
    key: "{{ env + '/services/' + service_name + '/future_id' }}"
    state: absent
