---
- name: Get consul pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: get
  vars:
    service: consul

- name: Stop current consul pod
  containers.podman.podman_pod:
    name: "{{ env + '-consul-' + current_pod }}"
    state: stopped
  when: current_pod != []
- name: Stop failed consul pod
  containers.podman.podman_pod:
    name: "{{ env + '-consul-' + failed_pod }}"
    state: stopped
  when: failed_pod != []

- name: Create consul volumes
  ansible.builtin.include_role:
    name: podman-volume
  vars:
    service: consul
    container_type: app
    volume_mountpoint: "{{ item }}"
  loop:
    - /etc/consul.d
    - /var/lib/consul

- name: Create consul pod
  ansible.builtin.import_role:
    name: podman-pod
  vars:
    service: consul
    pod_publish:
- name: Create consul container
  ansible.builtin.import_role:
    name: podman-container
  vars:
    service: consul
    container_image: "{{ lookup('consul_kv', env + '/defaults/registry_url', host=consul_host) + '/bootstrap/consul:latest' }}"
    container_type: app
    container_volumes:
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/consul.d'|replace('/', '-') }}:/etc/consul.d:z"
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/var/lib/consul'|replace('/', '-') }}:/var/lib/consul:z"
    container_secrets:

- name: Create consul mesh
  ansible.builtin.import_role:
    name: mesh
  vars:
    service: consul
    mesh_gateway:
    mesh_inbound:
      - service: consul-server
        protocol: tcp
        address: "127.0.0.1"
        port: "8300"
      - service: consul-lan-serf
        protocol: tcp
        address: "127.0.0.1"
        port: "8301"
      - service: consul-wan-serf
        protocol: tcp
        address: "127.0.0.1"
        port: "8302"
      - service: consul-api
        protocol: http
        address: "127.0.0.1"
        port: "8500"
      - service: consul-dns
        protocol: tcp
        address: "127.0.0.1"
        port: "8600"
    mesh_outbound:

- name: Set consul pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: set
  vars:
    service: consul
