---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          module
          enable
          nginx:1.22
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          nginx
          nginx-mod-stream
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "absent"
      loop:
        - "/etc/nginx/nginx.conf"
        - "/usr/share/nginx/html/index.html"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - "/usr/share/nginx/html/index.html"
    - ansible.posix.synchronize:
        src: rootfs/
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl enable etc-nginx-conf.d.path etc-nginx-stream.d.path nginx.service"
        - "buildah config --volume /etc/nginx/conf.d {{ container_uuid }}"
        - "buildah config --volume /etc/nginx/stream.d {{ container_uuid }}"
        - "buildah config --volume /etc/pki/tls/private {{ container_uuid }}"
        - "buildah config --volume /var/log/nginx {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
