---
- name: Get kuma id
  local_action:
    module: ansible.builtin.set_fact
    kuma_app_container_name: "{{ lookup('consul_kv', env + '/defaults/kuma_env', host=consul_host) + '-kuma-cp-' + lookup('consul_kv', env + '/defaults/kuma_id', host=consul_host) + '-app' }}"
  run_once: True
- name: Generate token
  ansible.builtin.command:
    cmd: "podman exec {{ kuma_app_container_name }} kumactl generate dataplane-token --mesh={{ env }} --name={{ future_app_container_name }}"
  register: mesh_token
- name: Get app container info
  containers.podman.podman_container_info:
    name: "{{ future_app_container_name }}"
  register: container_info
- name: Deploy mesh dataplane container
  ansible.builtin.include_role:
    name: podman-container
    tasks_from: present
  vars:
    container_name: "{{ future_mesh_container_name }}"
    container_pod: "{{ future_pod_name }}"
    container_image: "registry.lab.skarbek.name/bootstrap/base/kuma-dp:latest"
    container_type: mesh
    container_command:
      - /usr/local/bin/kuma-dp
      - run
      - --log-output-path=/var/log/kuma/kuma-dp.log
      - --cp-address=https://{{ lookup('consul_kv', env + '/defaults/kuma_ip', host=consul_host) }}:5678/
      - --dns-enabled=false
      - --dataplane-file=/etc/kuma/dataplane.yaml
      - --dataplane-token-file=/run/secrets/kuma-token
      - --config-dir=/run/kuma/envoy/
      - --dns-server-config-dir=/run/kuma/coredns/
    container_catatonit: true
    container_mount:
      - type=tmpfs,destination=/run/kuma
    container_secrets:
      - container_secret_name: "token"
        container_secret_data: "{{ mesh_token.stdout }}"
        container_secret_target: "kuma-token"
      - global_secret_name: "{{ env }}-kuma-config"
        global_secret_target: "kuma-config"
    container_volumes:
      - container_volume_mountpoint: /etc/kuma
        container_volume_type: zfs
        container_volume_files:
          template_files:
            - src: ../../pod-mesh/templates/dataplane.yaml.j2
              dest: /dataplane.yaml
      - container_volume_mountpoint: /var/log/kuma
        container_volume_type: zfs
- name: Start mesh dataplane container
  ansible.builtin.include_role:
    name: podman-container
    tasks_from: started
  vars:
    container_name: "{{ future_mesh_container_name }}"
