---
- name: Create kuma pod
  containers.podman.podman_pod:
    name: kuma-2201121344
    infra_image: "{{ pause_image }}"
    infra_name: kuma-2201121344-infra
    state: started
    ip: "10.88.1.2"
- name: Create kuma container
  containers.podman.podman_container:
    pod: "kuma-2201121344"
    name: "kuma-2201121344-app"
    image: "{{ registry_url }}/bootstrap/kuma-cp:latest"
    state: started
- name: Create kuma config
  containers.podman.podman_secret:
    name: kuma-config
    state: absent
- name: Create kuma config
  containers.podman.podman_secret:
    name: kuma-config
    data: "KUMA_CP_ADDRESS=https://10.88.1.2:5678/"
    state: present
- name: Create infra mesh
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - "podman cp mesh-infra.yaml kuma-2201121344-app:/run/kuma/mesh-infra.yaml"
    - "podman cp traffic-log-infra.yaml kuma-2201121344-app:/run/kuma/traffic-log-infra.yaml"
    - "podman exec kuma-2201121344-app kumactl apply -f /run/kuma/mesh-infra.yaml"
    - "podman exec kuma-2201121344-app kumactl apply -f /run/kuma/traffic-log-infra.yaml"
- name: Create mesh token
  containers.podman.podman_secret:
    name: kuma-2201121344-token
    state: absent
- name: Create mesh token
  ansible.builtin.shell:
    cmd: "podman exec kuma-2201121344-app kumactl generate dataplane-token --mesh=infra --name=kuma-2201121344|podman secret create kuma-2201121344-token -"
- name: Create mesh dataplanes
  ansible.builtin.copy:
    src: "dataplane.yaml"
    dest: "/var/lib/volumes/storage/kuma-2201121344-mesh-etc/_data/dataplane.yaml"
- name: Create mesh containers
  containers.podman.podman_container:
    pod: "kuma-2201121344"
    name: "kuma-2201121344-mesh"
    image: "{{ registry_url }}/bootstrap/kuma-dp:latest"
    secrets:
      - "kuma-2201121344-token,type=mount,target=kuma-token"
      - "kuma-config,type=mount"
    volumes:
      - "kuma-2201121344-mesh-etc:/etc/kuma:z"
    state: started
