---
- name: Get kuma pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: get

- name: Create kuma volumes
  ansible.builtin.include_role:
    name: podman-volume
  vars:
    service: kuma
    container_type: app
    volume_mountpoint: "{{ item }}"
  loop:
    - /etc/kuma
    - /var/log/kuma

- name: Create mesh config
  ansible.builtin.template:
    src: mesh.yaml.j2
    dest: "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/kuma'|replace('/', '-') }}/_data/{{ env }}-mesh.yaml"
- name: Create traffic-log config
  ansible.builtin.template:
    src: traffic-log.yaml.j2
    dest: "/var/lib/volumes/storage/{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/kuma'|replace('/', '-') }}/_data/{{ env }}-traffic-log.yaml"

- name: Create kuma pod
  ansible.builtin.import_role:
    name: podman-pod
  vars:
    service: kuma
    pod_publish:
- name: Create kuma container
  ansible.builtin.import_role:
    name: podman-container
  vars:
    service: kuma
    container_image: "{{ lookup('consul_kv', env + '/defaults/registry_url', host=consul_host) + '/bootstrap/kuma-cp:latest' }}"
    container_type: app
    container_volumes:
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/etc/kuma'|replace('/', '-') }}:/etc/kuma:z"
      - "{{ env + '-' + service + '-' + future_pod + '-app' + '/var/log/kuma'|replace('/', '-') }}:/var/log/kuma:z"
    container_secrets:

- name: Wait for kuma
  ansible.builtin.uri:
    url: "http://{{ container_info.container.NetworkSettings.IPAddress }}:5681/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
- name: Set kuma ip as default
  community.general.consul_kv:
    host: "{{ consul_host }}"
    key: "{{ env + '/defaults/kuma_ip' }}"
    value: "{{ container_info.container.NetworkSettings.IPAddress }}"
- name: Set kuma id as default
  community.general.consul_kv:
    host: "{{ consul_host }}"
    key: "{{ env + '/defaults/kuma_id' }}"
    value: "{{ future_pod }}"

- name: Remove config secret
  containers.podman.podman_secret:
    state: absent
    name: "{{ env + '-kuma-config' }}"
- name: Create config secret
  containers.podman.podman_secret:
    state: present
    name: "{{ env + '-kuma-config' }}"
    data: "KUMA_CP_ADDRESS=https://{{ container_info.container.NetworkSettings.IPAddress }}:5678/"

- name: Configure kuma
  ansible.builtin.command:
    cmd: "podman exec {{ env + '-' + service + '-' + future_pod + '-app' }} kumactl apply -f /etc/kuma/{{ item }}"
  loop:
    - "{{ env }}-mesh.yaml"
    - "{{ env }}-traffic-log.yaml"
- name: Create kuma mesh
  ansible.builtin.import_role:
    name: mesh
  vars:
    service: kuma
    mesh_inbound:
      - service: kuma
        protocol: http
        port: "5681"
        address: "127.0.0.1"
    mesh_outbound:

- name: Set kuma pod ids
  ansible.builtin.import_role:
    name: pod-id
    tasks_from: set
