FROM repo.skarbek.name/h-con-infra/python:latest

COPY rootfs/ /

RUN <<EOF
    microdnf -y install gcc python3.14-devel openldap-devel
    microdnf clean all
    uv pip install --python=/usr/bin/python3.14 --default-index=https://repo.skarbek.name/repository/p-ppi-pypi/simple apache-airflow[celery,otel,cncf-kubernetes,ldap,ftp,sftp,sqlite,imap,http,ssh,oracle,microsoft-mssql,gunicorn]==3.2.2 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.2.2/constraints-3.14.txt"
    uv cache clean
EOF

CMD ["/usr/bin/dinit", "-u", "-d", "/etc/dinit.d"]
