---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          systemd-journal-remote
          https://packages.timber.io/vector/{{ vector_version.split('-')[0] }}/vector-{{ vector_version }}.x86_64.rpm
      when: "not use_repository"
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          systemd-journal-remote
          vector-{{ vector_version }}
      when: "use_repository"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item.dest }}"
        state: "{{ item.state }}"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - dest: "/usr/share/vector"
          state: "directory"
          mode: "0755"
        - dest: "/etc/systemd/system/vector.service.d"
          state: "directory"
          mode: "0755"
        - dest: "/usr/share/vector/vector.yaml"
          state: "touch"
          mode: "0644"
        - dest: "/etc/systemd/system/vector.service.d/10-execstart.conf"
          state: "touch"
          mode: "0644"
        - dest: "/etc/tmpfiles.d/vector.conf"
          state: "touch"
          mode: "0644"
    - ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ container_path }}{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      loop:
        - src:  "usr/share/vector/vector.yaml"
          dest: "/usr/share/vector/vector.yaml"
        - src: "etc/systemd/system/vector.service.d/10-execstart.conf"
          dest: "/etc/systemd/system/vector.service.d/10-execstart.conf"
        - src: "etc/tmpfiles.d/vector.conf"
          dest: "/etc/tmpfiles.d/vector.conf"
    - ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl enable vector.service"
        - "buildah config --volume /etc/vector {{ container_uuid }}"
        - "buildah config --volume /var/lib/vector {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
