---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install {{ google_chrome_proxy_url }}
    - ansible.builtin.get_url:
        url: "{{ chrome_driver_proxy_url }}"
        dest: "{{ result_tempfile.path }}/chromedriver-linux64.zip"
        force: true
        owner: "root"
        group: "root"
        mode: "0644"
    - ansible.builtin.unarchive:
        src: "{{ result_tempfile.path }}/chromedriver-linux64.zip"
        dest: "{{ result_tempfile.path }}"
    - ansible.builtin.file:
        dest: "{{ container_path }}/usr/bin/chromedriver"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.copy:
        src: "{{ result_tempfile.path }}/chromedriver-linux64/chromedriver"
        dest: "{{ container_path }}/usr/bin/chromedriver"
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
