---
python:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - python/**/*
    - changes:
        - ubi10-minimal/**/*
  needs:
    - job: ubi10-minimal
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/python --network=host ./python/
    buildah push $REPO_URL/python
