FROM ghcr.io/mskarbek/containers/init:10.1

RUN dnf -y install\
 python3\
 python3-pip\
 python3-setuptools\
 python3-wheel\
 python3-pip-wheel\
 python3-setuptools-wheel;\
 dnf clean all;\
 cd /tmp;\
 curl -Lo uv.tar.gz https://github.com/astral-sh/uv/releases/download/0.9.27/uv-x86_64-unknown-linux-gnu.tar.gz;\
 tar xvf uv.tar.gz;\
 mv /tmp/uv-x86_64-unknown-linux-gnu/uvx /usr/local/bin/uvx;\
 mv /tmp/uv-x86_64-unknown-linux-gnu/uv /usr/local/bin/uv;\
 rm -rf /tmp/uv.tar.gz /tmp/uv-x86_64-unknown-linux-gnu
