default:
  tags:
    - buildah

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

stages:
  - build
  - push
  - trigger

build-image:
  stage: build
  before_script:
    - BASE_URL=`echo $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;"`
    - REPO_URL="$BASE_URL/cnt/meta.git"
    - REPO_DIR=../meta
    - rm -fr $REPO_DIR
    - git clone $REPO_URL $REPO_DIR
  script:
    - bash -ex ./build.sh

push-image:
  stage: push
  script:
    - skopeo copy containers-storage:$REGISTRY_URL/base/openjdk8-jre:latest oci:$REGISTRY_URL/base/openjdk8-jre:latest
    - skopeo copy containers-storage:$REGISTRY_URL/openjdk8-jre:latest oci:$REGISTRY_URL/openjdk8-jre:latest
  needs:
    - build-image

trigger-openjdk8-jdk:
  stage: trigger
  trigger: cnt/openjdk8-jdk
  needs:
    - push-image

trigger-nexus:
  stage: trigger
  trigger: cnt/nexus
  needs:
    - push-image
