---
ansible:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - ansible/**/*
    - changes:
        - ubi10/**/*
  needs:
    - job: ubi10
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/ansible --network=host ./ansible/
    buildah push $REPO_URL/ansible
