default:
  tags:
    - buildah

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

stages:
  - build
  - trigger

build-image:
  stage: build
  before_script:
    # downlowad meta repo
    - BASE_URL=`printf $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;"`
    - REPO_URL="$BASE_URL/containers/meta.git"
    - REPO_DIR=../meta
    - rm -fr $REPO_DIR
    - git clone $REPO_URL $REPO_DIR
    # source meta
    - source ../meta/common.sh
    # login to registry
    - skopeo_login
    # generate tag
    - export IMAGE_TAG=$(bash ../meta/tag.sh)
    - printf "IMAGE_TAG=$IMAGE_TAG" > ./build.env
  script:
    # build image
    - ./build.sh
    # tag repo
    - PUSH_URL=`printf $CI_REPOSITORY_URL | sed "s;:\/\/.*@;:\/\/oauth2:$CONTAINERS_CI_TOKEN@;"`
    - git remote add origin-tag $PUSH_URL
    - git tag v$IMAGE_TAG
    - git push -o ci.skip origin-tag --tags
    # push image
    - skopeo_copy base $IMAGE_TAG
  artifacts:
    reports:
      dotenv: ./build.env

trigger-golang:
  stage: trigger
  trigger: containers/golang
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-nodejs16:
  stage: trigger
  trigger: containers/nodejs16
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-openjdk11:
  stage: trigger
  trigger: containers/openjdk11
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-openjdk17:
  stage: trigger
  trigger: containers/openjdk17
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-openjdk8:
  stage: trigger
  trigger: containers/openjdk8
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-python3:
  stage: trigger
  trigger: containers/python3
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-rpmbuild:
  stage: trigger
  trigger: containers/rpmbuild
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-rust:
  stage: trigger
  trigger: containers/rust
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-systemd:
  stage: trigger
  trigger: containers/systemd
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image
