---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          systemd
          procps-ng
    - ansible.posix.synchronize:
        src: rootfs/
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.builtin.command:
        cmd: "buildah run --network none {{ container_uuid }} systemctl set-default multi-user.target"
    - ansible.builtin.command:
        cmd: >
          buildah run --network none {{ container_uuid }} systemctl mask
          console-getty.service
          dev-hugepages.mount
          dnf-makecache.timer
          getty.target
          kdump.service
          local-fs.target
          remote-fs.target
          swap.target
          sys-fs-fuse-connections.mount
          systemd-ask-password-console.path
          systemd-ask-password-wall.path
          systemd-firstboot.service
          systemd-homed.service
          systemd-logind.service
          systemd-machine-id-commit.service
          systemd-random-seed.service
          systemd-remount-fs.service
          systemd-resolved.service
          systemd-udev-trigger.service
          systemd-udevd.service
          veritysetup.target
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "absent"
      loop:
        - "/etc/machine-id"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
