---
- name: Generate deployment id
  ansible.builtin.include_role:
    name: pod-id
- name: Deploy generic pod
  ansible.builtin.include_role:
    name: podman-pod
    tasks_from: present
  vars:
    pod_name: "{{ current_pod_name }}"
- name: Deploy generic container
  ansible.builtin.include_role:
    name: podman-container
    tasks_from: present
  vars:
    container_name: "{{ current_app_container_name }}"
    container_pod: "{{ current_pod_name }}"
    container_image: "registry.access.redhat.com/ubi8/ubi:8.5"
    container_command: ["sleep", "300"]
    container_catatonit: true
    container_secrets:
      - container_secret_name: "some-secret"
        container_secret_data: "test value 1"
      - container_secret_name: "other-secret"
        container_secret_data: "test value 2"
        container_secret_target: "the-secret"
    container_volumes:
      - container_volume_mountpoint: /opt/1
        container_volume_type: local
        container_volume_files:
          copy_files:
            - src: generic-test-file
              dest: /app/test-file
          template_files:
            - src: generic-test-template.j2
              dest: /app/test-template
      - container_volume_mountpoint: /opt/2
        container_volume_type: zfs
        container_volume_files:
          copy_files:
            - src: generic-test-file
              dest: /app/test-file
          template_files:
            - src: generic-test-template.j2
              dest: /app/test-template
- name: Start generic pod
  ansible.builtin.include_role:
    name: podman-pod
    tasks_from: started
  vars:
    pod_name: "{{ current_pod_name }}"
- name: Start generic container
  ansible.builtin.include_role:
    name: podman-container
    tasks_from: started
  vars:
    container_name: "{{ current_app_container_name }}"
