---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          buildah
          containernetworking-plugins
          dnf
          fuse-overlayfs
          git-core
          git-lfs
          hostname
          openssh-clients
          rsync
          skopeo
          tar
          unzip
    - ansible.builtin.copy:
        src: "storage.conf"
        dest: "{{ container_path }}/etc/containers/storage.conf"
        owner: "root"
        group: "root"
        mode: "0644"
    - ansible.builtin.file:
        dest: "{{ container_path }}/usr/local/bin/terraform"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.file:
        dest: "{{ item }}"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - "{{ container_path }}/usr/local/share/terraform/plugins"
    - ansible.builtin.get_url:
        url: "{{ terraform_public_url }}"
        dest: "{{ result_tempfile.path }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        force: true
        owner: "root"
        group: "root"
        mode: "0644"
      when: "not use_repository"
    - ansible.builtin.get_url:
        url: "{{ terraform_proxy_url }}"
        dest: "{{ result_tempfile.path }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        force: true
        username: "{{ repository_username }}"
        password: "{{ repository_password }}"
        owner: "root"
        group: "root"
        mode: "0644"
      when: "use_repository"
    - ansible.builtin.unarchive:
        src: "{{ result_tempfile.path }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "{{ result_tempfile.path }}"
        #remote_src: true
    - ansible.builtin.copy:
        src: "{{ result_tempfile.path }}/terraform"
        dest: "{{ container_path }}/usr/local/bin/terraform"
        owner: "root"
        group: "root"
        mode: "0755"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
