#Type   Path                    Mode    User    Group   Age Argument
d       /run/caddy              0755    caddy   caddy   -   -
C       /etc/caddy/Caddyfile    -       -       -       -   /usr/share/caddy/Caddyfile
Z       /etc/caddy              -       caddy   caddy   -   -
