---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.file:
        dest: "{{ container_path }}{{ item }}"
        state: "touch"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - "/usr/local/bin/minio"
        - "/usr/local/bin/mcli"
    - ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ container_path }}/usr/local/bin/{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - url: "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.{{ minio_version }}"
          dest: "minio"
        - url: "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.{{ mcli_version }}"
          dest: "mcli"
    - ansible.posix.synchronize:
        src: "rootfs/"
        dest: "{{ container_path }}/"
        archive: false
        links: true
        recursive: true
        rsync_opts:
          - "--exclude=.gitkeep"
          - "--ignore-existing"
    - ansible.posix.command:
        cmd: "{{ item }}"
      loop:
        - "buildah run --network none {{ container_uuid }} systemctl enable minio.service"
        - "buildah config --volume /etc/minio {{ container_uuid }}"
        - "buildah config --volume /var/lib/minio {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
