FROM repo.skarbek.name/h-con-infra/ubi10:10.2

COPY rootfs/ /

RUN <<EOF
    curl -LO /usr/local/bin/garage https://garagehq.deuxfleurs.fr/_releases/v2.3.0/x86_64-unknown-linux-musl/garage
EOF

CMD ["/usr/bin/dinit", "--container"]

VOLUME /etc/garage

VOLUME /var/lib/garage
