---
zensical:
  tags:
    - dc02
  stage: build
  rules:
    - changes:
        - zensical/**/*
  needs:
    - job: python
      optional: true
  image: $REPO_URL/buildah:latest
  script: |
    buildah login -u $REPO_USERNAME -p $REPO_PASSWORD $REPO_URL
    buildah build -t $REPO_URL/zensical --network=host ./zensical/
    buildah push $REPO_URL/zensical
