default:
  tags:
    - buildah

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "pipeline"

stages:
  - build
  - trigger

build-image:
  stage: build
  before_script:
    # downlowad meta repo
    - BASE_URL=`printf $CI_REPOSITORY_URL | sed "s;\/*$CI_PROJECT_PATH.*;;"`
    - REPO_URL="$BASE_URL/containers/meta.git"
    - REPO_DIR=../meta
    - rm -fr $REPO_DIR
    - git clone $REPO_URL $REPO_DIR
    # source meta
    - source ../meta/common.sh
    # login to registry
    - skopeo_login
    # generate tag
    - export IMAGE_TAG=$(bash ../meta/tag.sh)
    - printf "IMAGE_TAG=$IMAGE_TAG" > ./build.env
  script:
    # build image
    - ./build.sh
    # tag repo
    - PUSH_URL=`printf $CI_REPOSITORY_URL | sed "s;:\/\/.*@;:\/\/oauth2:$CONTAINERS_CI_TOKEN@;"`
    - git remote add origin-tag $PUSH_URL
    - git tag v$IMAGE_TAG
    - git push -o ci.skip origin-tag --tags
    # push image
    - skopeo_copy openssh $IMAGE_TAG
  artifacts:
    reports:
      dotenv: ./build.env

trigger-rundeck-runner:
  stage: trigger
  trigger: containers/rundeck-runner
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-gitlab:
  stage: trigger
  trigger: containers/gitlab
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-toolbox:
  stage: trigger
  trigger: containers/toolbox
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image

trigger-host:
  stage: trigger
  trigger: containers/host
  variables:
    FROM_TAG: $IMAGE_TAG
  needs:
    - build-image
