#Type   Path                        Mode    User    Group   Age Argument
d       /run/openfga                0755    openfga openfga -   -
C       /etc/openfga/config.yaml    -       -       -       -   /usr/share/openfga/config.yaml
Z       /etc/openfga                -       openfga openfga -   -
