---
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/main.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
#    - ansible.builtin.dnf:
#        name:
#          - "nodejs"
#          - "npm"
#        conf_file: "{{ container_path }}/etc/dnf/dnf.conf"
#        install_weak_deps: false
#        state: "latest"
#        installroot: "{{ container_path }}"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          nodejs
          npm
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/systemd.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
    - ansible.builtin.command:
        cmd: "buildah config --cmd '[ \"/usr/sbin/init\" ]' {{ container_uuid }}"
    - ansible.builtin.command:
        cmd: "buildah config --stop-signal 'SIGRTMIN+3' {{ container_uuid }}"
    - ansible.builtin.command:
        cmd: "buildah config --volume /var/log/journal {{ container_uuid }}"
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
- hosts: "localhost"
  gather_facts: false
  vars_files:
    - "vars/common.yaml"
    - "vars/devel.yaml"
  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_create.yaml"
#    - ansible.builtin.dnf:
#        name:
#          - "git-core"
#          - "tar"
#          - "unzip"
#          - "gzip"
#          - "make"
#          - "gcc"
#          - "gcc-c++"
#        conf_file: "{{ container_path }}/etc/dnf/dnf.conf"
#        install_weak_deps: false
#        state: "latest"
#        installroot: "{{ container_path }}"
# Ansible DNF module issue:
# https://github.com/ansible/ansible/issues/80644
    - ansible.builtin.command:
        cmd: >
          dnf
          --quiet
          --assumeyes
          --disableplugin="subscription-manager"
          --config={{ container_path }}/etc/dnf/dnf.conf
          --installroot={{ container_path }}
          install
          git-core
          tar
          unzip
          gzip
          make
          gcc
          gcc-c++
    - ansible.builtin.import_tasks:
        file: "tasks/buildah_commit.yaml"
