name: c8s/base
on:
  #push:
  #  branches: 
  #    - main
  #  paths:
  #    - base
  workflow_dispatch:

env:
  CI_IMAGE: ghcr.io/mskarbek/bootstrap-c8s-buildah:latest
  IMAGE_NAME: base

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull CI image
        run: docker pull $CI_IMAGE
      - name: Run CI container
        run: |
          mkdir -vp $(pwd)/../storage
          docker run\
           -d\
           -v $(pwd):/root/containers\
           -v $(pwd)/../storage:/var/lib/containers\
           --name builder\
           --privileged\
           $CI_IMAGE
      - name: Build image
        timeout-minutes: 1
        run: |
          docker exec\
           -e IMMAGE_BOOTSTRAP=1\
           -e BASE_OS=c8s\
           -e REGISTRY_URL=registry.lab.skarbek.name\
           -w /root/containers/$IMAGE_NAME\
           builder bash -ex ./build.sh
