name: c8s/micro
on:
  #push:
  #  branches: 
  #    - main
  #  paths:
  #    - micro
  #    - .github/workflows/micro.yaml
  workflow_dispatch:

env:
  IMAGE_NAME: micro

jobs:
  micro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull CI image
        run: docker pull ubuntu:impish
      - name: Run CI container
        run: |
          mkdir -vp $(pwd)/../storage
          docker run\
           -d\
           -v $(pwd):/root/containers\
           -v $(pwd)/../storage:/var/lib/containers\
           --name builder\
           --privileged\
           ubuntu:impish\
           sleep 3600
      - name: Bootstrap CI container
        run: |
          docker exec -e DEBIAN_FRONTEND=noninteractive builder\
           apt-get -yq update
          docker exec -e DEBIAN_FRONTEND=noninteractive builder\
           apt-get -yq upgrade
          docker exec -e DEBIAN_FRONTEND=noninteractive builder\
           apt-get -yq install\
           dnf buildah rsync skopeo containers-storage
          docker exec builder\
           cp -v /usr/share/containers/storage.conf /etc/containers/storage.conf
          docker exec builder\
           sed -i 's/^driver = .*/driver = "vfs"/' /etc/containers/storage.conf
          docker exec builder\
           dnf -y install --releasever=8\
           http://centos.slaskdatacenter.com/8-stream/BaseOS/x86_64/os/Packages/centos-gpg-keys-8-4.el8.noarch.rpm\
           http://centos.slaskdatacenter.com/8-stream/BaseOS/x86_64/os/Packages/centos-stream-repos-8-4.el8.noarch.rpm\
           http://centos.slaskdatacenter.com/8-stream/BaseOS/x86_64/os/Packages/centos-stream-release-8.6-1.el8.noarch.rpm 
      - name: Build image
        timeout-minutes: 2
        run: |
          docker exec\
           -e IMMAGE_BOOTSTRAP=1\
           -e BASE_OS=c8s\
           -e REGISTRY_URL=registry.lab.skarbek.name\
           -w /root/containers/$IMAGE_NAME\
           builder bash -ex ./build.sh
