---
name: pgdog image
on:
  push:
    branches:
      - main
    paths:
      - "pgdog/**"
      - ".github/workflows/pgdog.yaml"
  workflow_dispatch:
env:
  REGISTRY: "ghcr.io"
  NAMESPACE: "mskarbek/containers"
  IMAGE_NAME: "pgdog"
  VERSION: "0.1.28"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
      - id: push
        uses: docker/build-push-action@v5
        with:
          context: ./pgdog/
          file: ./pgdog/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
